# S&P 500 by date

Get snapshot of S&P 500 components at a given date

In [1]:
from datetime import datetime
import os
import shutil
import pandas as pd

pd.options.mode.chained_assignment = None  # default='warn'
pd.set_option('display.max_rows', 600)

# -*- encoding: utf-8 -*-
%matplotlib inline

In [2]:
%%javascript
IPython.OutputArea.prototype._should_scroll = function(lines) {
    return false;
}

In [3]:
# Date to use for snapshot of S&P 500 components.
snap_shot = '2023-10-23'

In [4]:
def get_table(filename):

    if os.path.isfile(filename):
        df = pd.read_csv(filename, index_col='date')
        return df

In [5]:
filename = 'S&P 500 Historical Components & Changes (Updated).csv'
df = get_table(filename)
df.tail()

                                                      tickers
date
2026-04-09  A,AAPL,ABBV,ABNB,ABT,ACGL,ACN,ADBE,ADI,ADM,ADP...
2026-05-07  A,AAPL,ABBV,ABNB,ABT,ACGL,ACN,ADBE,ADI,ADM,ADP...
2026-05-21  A,AAPL,ABBV,ABNB,ABT,ACGL,ACN,ADBE,ADI,ADM,ADP...
2026-06-01  A,AAPL,ABBV,ABNB,ABT,ACGL,ACN,ADBE,ADI,ADM,ADP...
2026-06-02  A,AAPL,ABBV,ABNB,ABT,ACGL,ACN,ADBE,ADI,ADM,ADP...

In [6]:
# Convert ticker column from csv to list, then sort.
df['tickers'] = df['tickers'].apply(lambda x: sorted(x.split(',')))
df.tail()

                                                      tickers
date
2026-04-09  [A, AAPL, ABBV, ABNB, ABT, ACGL, ACN, ADBE, AD...
2026-05-07  [A, AAPL, ABBV, ABNB, ABT, ACGL, ACN, ADBE, AD...
2026-05-21  [A, AAPL, ABBV, ABNB, ABT, ACGL, ACN, ADBE, AD...
2026-06-01  [A, AAPL, ABBV, ABNB, ABT, ACGL, ACN, ADBE, AD...
2026-06-02  [A, AAPL, ABBV, ABNB, ABT, ACGL, ACN, ADBE, AD...

In [7]:
# Number of symbols in the first row.
l = list(df['tickers'].head(1))[0]
len(l)

487

In [8]:
# Get the synbols on snap_shot date by filtering df by rows before or on the snap_shot date,
# then picking the last row.
df2 = df[df.index <= snap_shot]
last_row = df2.tail(1)
last_row

                                                      tickers
date
2023-10-18  [A, AAL, AAPL, ABBV, ABNB, ABT, ACGL, ACN, ADB...

In [9]:
past = last_row['tickers'].iloc[0]
print('*'*40, f'S&P 500 on {snap_shot}', '*'*40)
print(past)

**************************************** S&P 500 on 2023-10-23 ****************************************
['A', 'AAL', 'AAPL', 'ABBV', 'ABNB', 'ABT', 'ACGL', 'ACN', 'ADBE', 'ADI', 'ADM', 'ADP', 'ADSK', 'AEE', 'AEP', 'AES', 'AFL', 'AIG', 'AIZ', 'AJG', 'AKAM', 'ALB', 'ALGN', 'ALL', 'ALLE', 'AMAT', 'AMCR', 'AMD', 'AME', 'AMGN', 'AMP', 'AMT', 'AMZN', 'ANET', 'ANSS', 'AON', 'AOS', 'APA', 'APD', 'APH', 'APTV', 'ARE', 'ATO', 'AVB', 'AVGO', 'AVY', 'AWK', 'AXON', 'AXP', 'AZO', 'BA', 'BAC', 'BALL', 'BAX', 'BBWI', 'BBY', 'BDX', 'BEN', 'BF.B', 'BG', 'BIIB', 'BIO', 'BK', 'BKNG', 'BKR', 'BLDR', 'BLK', 'BMY', 'BR', 'BRK.B', 'BRO', 'BSX', 'BWA', 'BX', 'BXP', 'C', 'CAG', 'CAH', 'CARR', 'CAT', 'CB', 'CBOE', 'CBRE', 'CCI', 'CCL', 'CDAY', 'CDNS', 'CDW', 'CE', 'CEG', 'CF', 'CFG', 'CHD', 'CHRW', 'CHTR', 'CI', 'CINF', 'CL', 'CLX', 'CMA', 'CMCSA', 'CME', 'CMG', 'CMI', 'CMS', 'CNC', 'CNP', 'COF', 'COO', 'COP', 'COR', 'COST', 'CPB', 'CPRT', 'CPT', 'CRL', 'CRM', 'CSCO', 'CSGP', 'CSX', 'CTAS', 'CTLT', 'CTRA', 'CTSH', 'CTVA', 'CVS', 'CVX', 'CZR', 'D', 'DAL', 'DD', 'DE', 'DFS', 'DG', 'DGX', 'DHI', 'DHR', 'DIS', 'DLR', 'DLTR', 'DOV', 'DOW', 'DPZ', 'DRI', 'DTE', 'DUK', 'DVA', 'DVN', 'DXCM', 'EA', 'EBAY', 'ECL', 'ED', 'EFX', 'EG', 'EIX', 'EL', 'ELV', 'EMN', 'EMR', 'ENPH', 'EOG', 'EPAM', 'EQIX', 'EQR', 'EQT', 'ES', 'ESS', 'ETN', 'ETR', 'ETSY', 'EVRG', 'EW', 'EXC', 'EXPD', 'EXPE', 'EXR', 'F', 'FANG', 'FAST', 'FCX', 'FDS', 'FDX', 'FE', 'FFIV', 'FI', 'FICO', 'FIS', 'FITB', 'FLT', 'FMC', 'FOX', 'FOXA', 'FRT', 'FSLR', 'FTNT', 'FTV', 'GD', 'GE', 'GEHC', 'GEN', 'GILD', 'GIS', 'GL', 'GLW', 'GM', 'GNRC', 'GOOG', 'GOOGL', 'GPC', 'GPN', 'GRMN', 'GS', 'GWW', 'HAL', 'HAS', 'HBAN', 'HCA', 'HD', 'HES', 'HIG', 'HII', 'HLT', 'HOLX', 'HON', 'HPE', 'HPQ', 'HRL', 'HSIC', 'HST', 'HSY', 'HUBB', 'HUM', 'HWM', 'IBM', 'ICE', 'IDXX', 'IEX', 'IFF', 'ILMN', 'INCY', 'INTC', 'INTU', 'INVH', 'IP', 'IPG', 'IQV', 'IR', 'IRM', 'ISRG', 'IT', 'ITW', 'IVZ', 'J', 'JBHT', 'JBL', 'JCI', 'JKHY', 'JNJ', 'JNPR', 'JPM', 'K', 'KDP', 'KEY', 'KEYS', 'KHC', 'KIM', 'KLAC', 'KMB', 'KMI', 'KMX', 'KO', 'KR', 'KVUE', 'L', 'LDOS', 'LEN', 'LH', 'LHX', 'LIN', 'LKQ', 'LLY', 'LMT', 'LNT', 'LOW', 'LRCX', 'LULU', 'LUV', 'LVS', 'LW', 'LYB', 'LYV', 'MA', 'MAA', 'MAR', 'MAS', 'MCD', 'MCHP', 'MCK', 'MCO', 'MDLZ', 'MDT', 'MET', 'META', 'MGM', 'MHK', 'MKC', 'MKTX', 'MLM', 'MMC', 'MMM', 'MNST', 'MO', 'MOH', 'MOS', 'MPC', 'MPWR', 'MRK', 'MRNA', 'MRO', 'MS', 'MSCI', 'MSFT', 'MSI', 'MTB', 'MTCH', 'MTD', 'MU', 'NCLH', 'NDAQ', 'NDSN', 'NEE', 'NEM', 'NFLX', 'NI', 'NKE', 'NOC', 'NOW', 'NRG', 'NSC', 'NTAP', 'NTRS', 'NUE', 'NVDA', 'NVR', 'NWS', 'NWSA', 'NXPI', 'O', 'ODFL', 'OKE', 'OMC', 'ON', 'ORCL', 'ORLY', 'OTIS', 'OXY', 'PANW', 'PARA', 'PAYC', 'PAYX', 'PCAR', 'PCG', 'PEAK', 'PEG', 'PEP', 'PFE', 'PFG', 'PG', 'PGR', 'PH', 'PHM', 'PKG', 'PLD', 'PM', 'PNC', 'PNR', 'PNW', 'PODD', 'POOL', 'PPG', 'PPL', 'PRU', 'PSA', 'PSX', 'PTC', 'PWR', 'PXD', 'PYPL', 'QCOM', 'QRVO', 'RCL', 'REG', 'REGN', 'RF', 'RHI', 'RJF', 'RL', 'RMD', 'ROK', 'ROL', 'ROP', 'ROST', 'RSG', 'RTX', 'RVTY', 'SBAC', 'SBUX', 'SCHW', 'SHW', 'SJM', 'SLB', 'SNA', 'SNPS', 'SO', 'SPG', 'SPGI', 'SRE', 'STE', 'STLD', 'STT', 'STX', 'STZ', 'SWK', 'SWKS', 'SYF', 'SYK', 'SYY', 'T', 'TAP', 'TDG', 'TDY', 'TECH', 'TEL', 'TER', 'TFC', 'TFX', 'TGT', 'TJX', 'TMO', 'TMUS', 'TPR', 'TRGP', 'TRMB', 'TROW', 'TRV', 'TSCO', 'TSLA', 'TSN', 'TT', 'TTWO', 'TXN', 'TXT', 'TYL', 'UAL', 'UBER', 'UDR', 'UHS', 'ULTA', 'UNH', 'UNP', 'UPS', 'URI', 'USB', 'V', 'VFC', 'VICI', 'VLO', 'VLTO', 'VMC', 'VRSK', 'VRSN', 'VRTX', 'VTR', 'VTRS', 'VZ', 'WAB', 'WAT', 'WBA', 'WBD', 'WDC', 'WEC', 'WELL', 'WFC', 'WHR', 'WM', 'WMB', 'WMT', 'WRB', 'WRK', 'WST', 'WTW', 'WY', 'WYNN', 'XEL', 'XOM', 'XRAY', 'XYL', 'YUM', 'ZBH', 'ZBRA', 'ZION', 'ZTS']

In [10]:
# Get current S&P500 list.
filename = 'sp500.csv'
current = pd.read_csv(filename)
current = sorted(list(current['Symbol']))
#print(current)

In [11]:
# Show what's been added and removed since snap_shot date.

added = list(set(current) - set(past))
print('*'*40, f'ADDED since {snap_shot}', '*'*40)
print(added)
print()

removed = list(set(past) - set(current))
print('*'*40, f'REMOVED since {snap_shot}', '*'*40)
print(removed)

**************************************** ADDED since 2023-10-23 ****************************************
['Q', 'XYZ', 'COIN', 'DOC', 'CVNA', 'APP', 'GEV', 'TPL', 'GDDY', 'BNY', 'VEEV', 'TTD', 'KKR', 'FIX', 'CRH', 'DDOG', 'CRWD', 'COHR', 'IBKR', 'SMCI', 'CIEN', 'FDXF', 'SATS', 'DECK', 'EME', 'VST', 'APO', 'DELL', 'SOLV', 'PSKY', 'FISV', 'EXE', 'ERIE', 'VRT', 'PLTR', 'TKO', 'WSM', 'DASH', 'MRSH', 'LITE', 'SW', 'HOOD', 'CPAY', 'WDAY', 'LII', 'SNDK', 'ARES', 'CASY']

**************************************** REMOVED since 2023-10-23 ****************************************
['RHI', 'MHK', 'XRAY', 'BWA', 'BK', 'ENPH', 'QRVO', 'WHR', 'JNPR', 'MRO', 'ANSS', 'PXD', 'FI', 'FMC', 'WRK', 'PEAK', 'BBWI', 'PAYC', 'MKTX', 'LKQ', 'TFX', 'VFC', 'CZR', 'HOLX', 'WBA', 'ILMN', 'K', 'IPG', 'CE', 'CTRA', 'EMN', 'CDAY', 'BIO', 'AAL', 'CTLT', 'KMX', 'ZION', 'DFS', 'FLT', 'ETSY', 'PARA', 'CMA', 'MMC', 'MOH', 'LW', 'EPAM', 'HES', 'MTCH']